version: "3"
services:
  vue:
    build: .
    tty: true
    ports:
      - 8080:8080
    volumes: 
      - .:/app
    working_dir: /app
    container_name: vue
    command:
      - /bin/sh 
      - -c
      - |
        cd /app/docs
        yarn dev 

